name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    name: "PHPUnit: MW ${{ matrix.mw }}, PHP ${{ matrix.php }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          # Current Long-Term Support release
          - mw: 'REL1_43'
            php: '8.1'
          # Legacy stable release
          - mw: 'REL1_45'
            php: '8.2'
          # Current stable release
          - mw: 'REL1_46'
            php: '8.2'
          # Development branch, to catch breakage early
          - mw: 'master'
            php: '8.3'
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.mw == 'master' }}
    steps:
      # check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test extension
        uses: wikiteq/mediawiki-phpunit-action@v2
        with:
          type: extension
          php: ${{ matrix.php }}
          mwbranch: ${{ matrix.mw }}
          extension: PubmedParser
          testgroup: extension-PubmedParser
